### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by mamimamis** [Codeusa/Borderless-Gaming#340]
# Crash log:

`
?Unconsumed data left in the buffer; this suggests corrupt inputProtoExceptionÌ   at ProtoBuf.ProtoReader.CheckFullyConsumed()
   at ProtoBuf.Meta.TypeModel.Deserialize(Stream source, Object value, Type type, SerializationContext context)
   at ProtoBuf.Serializer.Deserialize[T](Stream source)
   at BorderlessGaming.Logic.Windows.Security.LoadConfigFile() in E:\Dev\Borderless-Gaming\BorderlessGaming.Logic\Windows\Security.cs:line 39
   at BorderlessGaming.Logic.Models.Config.Load() in E:\Dev\Borderless-Gaming\BorderlessGaming.Logic\Models\Config.cs:line 39
   at BorderlessGaming.Logic.System.Tools.Setup() in E:\Dev\Borderless-Gaming\BorderlessGaming.Logic\System\Tools.cs:line 70
   at BorderlessGaming.Program.Main() in E:\Dev\Borderless-Gaming\BorderlessGaming\Program.cs:line 24`

**Comment by interdom3** [comment]
I have the same issue:


?Unconsumed data left in the buffer; this suggests corrupt inputProtoException‘    at ProtoBuf.ProtoReader.CheckFullyConsumed() in c:\code\protobuf-net\src\protobuf-net\ProtoReader.cs:line 1357
   at ProtoBuf.Meta.TypeModel.Deserialize(Stream source, Object value, Type type, SerializationContext context) in c:\code\protobuf-net\src\protobuf-net\Meta\TypeModel.cs:line 610
   at ProtoBuf.Serializer.Deserialize[T](Stream source) in c:\code\protobuf-net\src\protobuf-net\Serializer.cs:line 77
   at BorderlessGaming.Logic.Windows.Security.LoadConfigFile() in E:\Dev\Borderless-Gaming\BorderlessGaming.Logic\Windows\Security.cs:line 39
   at BorderlessGaming.Logic.Models.Config.Load() in E:\Dev\Borderless-Gaming\BorderlessGaming.Logic\Models\Config.cs:line 39
   at BorderlessGaming.Logic.System.Tools.Setup() in E:\Dev\Borderless-Gaming\BorderlessGaming.Logic\System\Tools.cs:line 70
   at BorderlessGaming.Program.Main() in E:\Dev\Borderless-Gaming\BorderlessGaming\Program.cs:line 24

**Comment by willl03** [comment]
Same, I've been using this program without issue for months, no hardware change, and now:
?Unconsumed data left in the buffer; this suggests corrupt inputProtoExceptionÌ   at ProtoBuf.ProtoReader.CheckFullyConsumed()
   at ProtoBuf.Meta.TypeModel.Deserialize(Stream source, Object value, Type type, SerializationContext context)
   at ProtoBuf.Serializer.Deserialize[T](Stream source)
   at BorderlessGaming.Logic.Windows.Security.LoadConfigFile() in E:\Dev\Borderless-Gaming\BorderlessGaming.Logic\Windows\Security.cs:line 39
   at BorderlessGaming.Logic.Models.Config.Load() in E:\Dev\Borderless-Gaming\BorderlessGaming.Logic\Models\Config.cs:line 39
   at BorderlessGaming.Logic.System.Tools.Setup() in E:\Dev\Borderless-Gaming\BorderlessGaming.Logic\System\Tools.cs:line 70
   at BorderlessGaming.Program.Main() in E:\Dev\Borderless-Gaming\BorderlessGaming\Program.cs:line 24

**Comment by willl03** [comment]
I uninstalled the version I had, purchased & reinstalled on Steam, it works now. I really appreciate this program, thanks Andrew!!

**Comment by PointyDev** [comment]
Getting the same error:
```
?Unconsumed data left in the buffer; this suggests corrupt inputProtoException‘   at ProtoBuf.ProtoReader.CheckFullyConsumed() in c:\code\protobuf-net\src\protobuf-net\ProtoReader.cs:line 1357
   at ProtoBuf.Meta.TypeModel.Deserialize(Stream source, Object value, Type type, SerializationContext context) in c:\code\protobuf-net\src\protobuf-net\Meta\TypeModel.cs:line 610
   at ProtoBuf.Serializer.Deserialize[T](Stream source) in c:\code\protobuf-net\src\protobuf-net\Serializer.cs:line 77
   at BorderlessGaming.Logic.Windows.Security.LoadConfigFile() in E:\Dev\Borderless-Gaming\BorderlessGaming.Logic\Windows\Security.cs:line 39
   at BorderlessGaming.Logic.Models.Config.Load() in E:\Dev\Borderless-Gaming\BorderlessGaming.Logic\Models\Config.cs:line 39
   at BorderlessGaming.Logic.System.Tools.Setup() in E:\Dev\Borderless-Gaming\BorderlessGaming.Logic\System\Tools.cs:line 70
   at BorderlessGaming.Program.Main() in E:\Dev\Borderless-Gaming\BorderlessGaming\Program.cs:line 24
```
Borderless Gaming version: 9.4.9.1328
System information: 

![](https://pointy.needs-to-s.top/507195.png)
