### ISSUE TITLE
Unhandled exception [9.4.9]

### ISSUE THREAD

**Issue by Keith94** [Codeusa/Borderless-Gaming#341]
>BProcess has exited, so the requested information is not available.InvalidOperationException¤   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_ProcessName()
   at BorderlessGaming.Logic.Core.ProcessWatcher.<UpdateProcesses>b__20_2(ProcessDetails pd) in E:\Dev\Borderless-Gaming\BorderlessGaming.Logic\Core\ProcessWatcher.cs:line 208
   at BorderlessGaming.Logic.Windows.Native.QueryProcessesWithWindows(Action`1 callback, List`1 windowPtrSet) in E:\Dev\Borderless-Gaming\BorderlessGaming.Logic\Windows\Native.cs:line 439
   at BorderlessGaming.Logic.Core.ProcessWatcher.UpdateProcesses() in E:\Dev\Borderless-Gaming\BorderlessGaming.Logic\Core\ProcessWatcher.cs:line 206
   at BorderlessGaming.Logic.Core.ProcessWatcher.<Watch>d__15.MoveNext() in E:\Dev\Borderless-Gaming\BorderlessGaming.Logic\Core\ProcessWatcher.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by Codeusa** [comment]
Will be fixed in the next update (This Friday)

**Comment by m-alice** [comment]
[UnhandledException_30.08.2017.zip](https://github.com/Codeusa/Borderless-Gaming/files/1264349/UnhandledException_30.08.2017.zip)
Report Attached. Thx in advance.

**Comment by Keith94** [comment]
Any update soon?

**Comment by RaTcHeT302** [comment]
@Keith94 Download Everything Search.
https://www.voidtools.com/downloads/

Run it. Under Search, select Match Path.
Search for Borderless Gaming or BorderlessGaming and search for Borderless Gaming in any AppData folders.
Delete everything, and I mean everything related to Borderless Gaming, no matter which folder it is in.
Reinstall Borderless Gaming.

That's how I got rid of the issue, as my pc turned off a bunch of times during a short power outage.

**Comment by m-alice** [comment]
Again. After (maybe in playing time) "Dying Light" game (added, 1920x1050).
[UnhandledException_08.02.2018.zip](https://github.com/Codeusa/Borderless-Gaming/files/1706380/UnhandledException_08.02.2018.zip)
