### ISSUE TITLE
crash without game

### ISSUE THREAD

**Issue by PTlooNy** [Codeusa/Borderless-Gaming#353]
had this error a couple of times recently with no game activity
Borderless Gaming 9.4.9.1328

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	BorderlessGaming.exe
  Problem Signature 02:	9.4.9.1328
  Problem Signature 03:	595d36c1
  Problem Signature 04:	System
  Problem Signature 05:	4.7.2114.0
  Problem Signature 06:	59a63a25
  Problem Signature 07:	2f3c
  Problem Signature 08:	13a
  Problem Signature 09:	System.InvalidOperationException
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	3081
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by PTlooNy** [comment]
log file >>>

BProcess has exited, so the requested information is not available.InvalidOperationException¤   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_ProcessName()
   at BorderlessGaming.Logic.Core.ProcessWatcher.<UpdateProcesses>b__20_2(ProcessDetails pd) in E:\Dev\Borderless-Gaming\BorderlessGaming.Logic\Core\ProcessWatcher.cs:line 208
   at BorderlessGaming.Logic.Windows.Native.QueryProcessesWithWindows(Action`1 callback, List`1 windowPtrSet) in E:\Dev\Borderless-Gaming\BorderlessGaming.Logic\Windows\Native.cs:line 439
   at BorderlessGaming.Logic.Core.ProcessWatcher.UpdateProcesses() in E:\Dev\Borderless-Gaming\BorderlessGaming.Logic\Core\ProcessWatcher.cs:line 206
   at BorderlessGaming.Logic.Core.ProcessWatcher.<Watch>d__15.MoveNext() in E:\Dev\Borderless-Gaming\BorderlessGaming.Logic\Core\ProcessWatcher.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by Tealk144** [comment]
have the same problem

```
TDie angeforderten Informationen sind nicht verfÃ¼gbar, da der Prozess beendet wurde.InvalidOperationExceptionÿ	   bei System.Diagnostics.Process.EnsureState(State state)
   bei System.Diagnostics.Process.get_ProcessName()
   bei BorderlessGaming.Logic.Core.ProcessWatcher.<UpdateProcesses>b__20_2(ProcessDetails pd)
   bei BorderlessGaming.Logic.Windows.Native.QueryProcessesWithWindows(Action`1 callback, List`1 windowPtrSet)
   bei BorderlessGaming.Logic.Core.ProcessWatcher.UpdateProcesses()
   bei BorderlessGaming.Logic.Core.ProcessWatcher.<Watch>d__15.MoveNext()
--- Ende der StapelÃ¼berwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelÃ¶st wurde ---
   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   bei System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   bei System.Threading.ThreadPoolWorkQueue.Dispatch()
   bei System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by Codeusa** [comment]
Fixed in the latest Steam build

**Comment by RudyTheNinja** [comment]
Hey guys I think I'm having the exact same problem 

![image](https://user-images.githubusercontent.com/45320386/77488404-5ee80a80-6df2-11ea-8c1f-9ea3a70212ae.png)

`Fault bucket 1867414804347635487, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: BorderlessGaming.exe
P2: 9.5.6.1328
P3: 5d228039
P4: mscorlib
P5: 4.8.4150.0
P6: 5e176d21
P7: 1693
P8: fc
P9: System.IO.DirectoryNotFound
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF025.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF084.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF0A4.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF0A2.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF0C2.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_BorderlessGaming_7655b5f8abeaeceb61262a811d9b48289abaf6_f87e3e26_defc5d45-0434-4222-a40d-50a05201da86

Analysis symbol: 
Rechecking for solution: 0
Report Id: 37c1747b-4e22-4ae1-8c1d-481b11700e38
Report Status: 268435456
Hashed bucket: 0c3b76b2e550130a49ea63dedd72471f
Cab Guid: 0`

I've already:
Reinstalled this and a previous version
Rolled back to win 1903
Turned off antivirus
And I can't remember the rest, my issue is #476 

How else do I make sure that all traces of BG are gone so i can actually do a clean reinstall?
I can't find any info of it in appdata so it must be under a different name I don't know of
