### ISSUE TITLE
Crash when starting

### ISSUE THREAD

**Issue by xMate420x** [Codeusa/Borderless-Gaming#360]
# Crash log:
?Unconsumed data left in the buffer; this suggests corrupt inputProtoException˛   a kĂ¶vetkezĹ‘ helyen: ProtoBuf.ProtoReader.CheckFullyConsumed() hely: c:\code\protobuf-net\src\protobuf-net\ProtoReader.cs, sor: 1357
   a kĂ¶vetkezĹ‘ helyen: ProtoBuf.Meta.TypeModel.Deserialize(Stream source, Object value, Type type, SerializationContext context) hely: c:\code\protobuf-net\src\protobuf-net\Meta\TypeModel.cs, sor: 610
   a kĂ¶vetkezĹ‘ helyen: ProtoBuf.Serializer.Deserialize[T](Stream source) hely: c:\code\protobuf-net\src\protobuf-net\Serializer.cs, sor: 77
   a kĂ¶vetkezĹ‘ helyen: BorderlessGaming.Logic.Windows.Security.LoadConfigFile() hely: E:\Dev\Borderless-Gaming\BorderlessGaming.Logic\Windows\Security.cs, sor: 39
   a kĂ¶vetkezĹ‘ helyen: BorderlessGaming.Logic.Models.Config.Load() hely: E:\Dev\Borderless-Gaming\BorderlessGaming.Logic\Models\Config.cs, sor: 39
   a kĂ¶vetkezĹ‘ helyen: BorderlessGaming.Logic.System.Tools.Setup() hely: E:\Dev\Borderless-Gaming\BorderlessGaming.Logic\System\Tools.cs, sor: 70
   a kĂ¶vetkezĹ‘ helyen: BorderlessGaming.Program.Main() hely: E:\Dev\Borderless-Gaming\BorderlessGaming\Program.cs, sor: 24

**Comment by Masterfireheart** [comment]
I'm having the same issue, Windows 10 1709


**?Unconsumed data left in the buffer; this suggests corrupt inputProtoException‘   at ProtoBuf.ProtoReader.CheckFullyConsumed() in c:\code\protobuf-net\src\protobuf-net\ProtoReader.cs:line 1357
   at ProtoBuf.Meta.TypeModel.Deserialize(Stream source, Object value, Type type, SerializationContext context) in c:\code\protobuf-net\src\protobuf-net\Meta\TypeModel.cs:line 610
   at ProtoBuf.Serializer.Deserialize[T](Stream source) in c:\code\protobuf-net\src\protobuf-net\Serializer.cs:line 77
   at BorderlessGaming.Logic.Windows.Security.LoadConfigFile() in E:\Dev\Borderless-Gaming\BorderlessGaming.Logic\Windows\Security.cs:line 39
   at BorderlessGaming.Logic.Models.Config.Load() in E:\Dev\Borderless-Gaming\BorderlessGaming.Logic\Models\Config.cs:line 39
   at BorderlessGaming.Logic.System.Tools.Setup() in E:\Dev\Borderless-Gaming\BorderlessGaming.Logic\System\Tools.cs:line 70
   at BorderlessGaming.Program.Main() in E:\Dev\Borderless-Gaming\BorderlessGaming\Program.cs:line 24**
