### ISSUE TITLE
Crashes due to unicode characters somewhere , present in 9.9.4 and 9.9.5

### ISSUE THREAD

**Issue by Ryonez** [Codeusa/Borderless-Gaming#429]
![image](https://user-images.githubusercontent.com/16157130/51038477-383c1a80-1618-11e9-9abd-0a7031247970.png)

```
PUnable to translate Unicode character \uDE98 at index 99 to specified code page.EncoderFallbackException¡   at System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   at System.Text.EncoderFallbackBuffer.InternalFallback(Char ch, Char*& chars)
   at System.Text.UTF8Encoding.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, EncoderNLS baseEncoder)
   at System.Text.EncoderNLS.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, Boolean flush)
   at System.Text.EncoderNLS.GetBytes(Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex, Boolean flush)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Write(Char[] buffer, Int32 index, Int32 count)
   at System.IO.TextWriter.WriteLine(String value)
   at System.IO.TextWriter.SyncTextWriter.WriteLine(String value)
   at System.Console.WriteLine(String value)
   at BorderlessGaming.Logic.Windows.Native.GetWindowTitle(IntPtr hWnd)
   at BorderlessGaming.Logic.Models.ProcessDetails..ctor(Process p, IntPtr hWnd)
   at BorderlessGaming.Logic.Windows.Native.QueryProcessesWithWindows(Action`1 callback, List`1 windowPtrSet)
   at BorderlessGaming.Logic.Core.ProcessWatcher.<UpdateProcesses>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BorderlessGaming.Logic.Core.ProcessWatcher.<Watch>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

I don't know what could be triggering this.

**Comment by Codeusa** [comment]
Interesting. I'll fix it this weekend.

**Comment by GT500org** [comment]
I just wanted to report that I've been having similar crashes. I saved a dump with Process Hacker before click "OK" in the dialog notifying me of the crash:
https://www.gt500.org/debug/borderlessgaming/Crash_2019-Jan-21.7z

At first glance the log appears similar:

`
QUnable to translate Unicode character \uDF38 at index 122 to specified code page.EncoderFallbackExceptionÅ   at System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   at System.Text.EncoderFallbackBuffer.InternalFallback(Char ch, Char*& chars)
   at System.Text.UTF8Encoding.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, EncoderNLS baseEncoder)
   at System.Text.EncoderNLS.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, Boolean flush)
   at System.Text.EncoderNLS.GetBytes(Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex, Boolean flush)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Write(Char[] buffer, Int32 index, Int32 count)
   at System.IO.TextWriter.WriteLine(String value)
   at System.IO.TextWriter.SyncTextWriter.WriteLine(String value)
   at System.Console.WriteLine(String value)
   at BorderlessGaming.Logic.Windows.Native.GetWindowTitle(IntPtr hWnd) in E:\Dev\BG\Borderless-Gaming\BorderlessGaming.Logic\Windows\Native.cs:line 223
   at BorderlessGaming.Logic.Models.ProcessDetails..ctor(Process p, IntPtr hWnd) in E:\Dev\BG\Borderless-Gaming\BorderlessGaming.Logic\Models\ProcessDetails.cs:line 31
   at BorderlessGaming.Logic.Windows.Native.QueryProcessesWithWindows(Action`1 callback, List`1 windowPtrSet) in E:\Dev\BG\Borderless-Gaming\BorderlessGaming.Logic\Windows\Native.cs:line 436
   at BorderlessGaming.Logic.Core.ProcessWatcher.<UpdateProcesses>d__20.MoveNext() in E:\Dev\BG\Borderless-Gaming\BorderlessGaming.Logic\Core\ProcessWatcher.cs:line 206
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BorderlessGaming.Logic.Core.ProcessWatcher.<Watch>d__15.MoveNext() in E:\Dev\BG\Borderless-Gaming\BorderlessGaming.Logic\Core\ProcessWatcher.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()`

**Comment by kevinvanrijn** [comment]
#430

**Comment by Ryonez** [comment]
Can we get this fixed please @Codeusa? I'm starting to get very frustrated that it's crashing constantly.

**Comment by GT500org** [comment]
@Ryonez I don't think there's going to be any future updates to this program (at least not anytime soon).

I downgraded to version 9.5.0, as that version isn't effected by this crashing issue:
https://github.com/Codeusa/Borderless-Gaming/releases/tag/9.5

**Comment by Ryonez** [comment]
Looks like I'll have to. Seem the whole project is slowly shifting into abandonware after #417.

**Comment by Ryonez** [comment]
@Codeusa This is good, any idea on the release time?

**Comment by Ryonez** [comment]
@Codeusa 

I've waited for 18 days since you made the release announcement, however the release still hasn't been pushed out.

The **current Steam version is 9.5.5**

I think I'll rollback to 9.5 permanently. I haven't had any issues with it and the only major change since seems to be an ad for Rainway.

**Comment by GT500org** [comment]
@Ryonez I would believe the Rainway banner was added in 9.5.1 (or later). I have 9.5.0 installed, and have yet to see it.

**Comment by GT500org** [comment]
https://github.com/Codeusa/Borderless-Gaming/releases/tag/9.5.6

I installed 9.5.6 last night, and have yet to have a single crash. Granted I haven't actually used it with a game yet, however I don't remember the crashes only happening when playing a game that Borderless Gaming was forcing into a borderless window.
