### ISSUE TITLE
BG is freezing constantly all of a sudden

### ISSUE THREAD

**Issue by Mapsking** [Codeusa/Borderless-Gaming#516]
The program has worked for me very well, until recently, it freezes up on me.  It seems to work the first time I run a program, but then, when I run the program later, nothing happens.  The icon is still in the System Tray, on Windows 10 x64.  I can right click it, and it gives me the option to close it, but it won't close it.  If I double-click on it to open it, it will open, but sometimes shows an hourglass cursor, or the regular mouse pointer, but still, it is frozen, and will not allow me to refresh it, or do anything, other than force-closing it and ending the process with Task Manager.  Not sure what changed, other than a possible Windows update, however, here is a crash log from yesterday.  Is there anything I can do to restore functionality?

Error creating window handle.Win32ExceptionÙ	   at System.Windows.Forms.NativeWindow.CreateHandle(CreateParams cp)
   at System.Windows.Forms.Timer.TimerNativeWindow.EnsureHandle()
   at System.Windows.Forms.Timer.TimerNativeWindow.StartTimer(Int32 interval)
   at System.Windows.Forms.Timer.set_Enabled(Boolean value)
   at System.Windows.Forms.ToolStripManager.ModalMenuFilter.ProcessMessages(Boolean process)
   at System.Windows.Forms.ToolStripManager.ModalMenuFilter.EnterMenuModeCore()
   at System.Windows.Forms.ToolStripManager.ModalMenuFilter.SetActiveToolStripCore(ToolStrip toolStrip)
   at System.Windows.Forms.ToolStripDropDown.ReparentToActiveToolStripWindow()
   at System.Windows.Forms.ToolStripDropDown.SetVisibleCore(Boolean visible)
   at System.Windows.Forms.ContextMenuStrip.SetVisibleCore(Boolean visible)
   at System.Windows.Forms.ToolStripDropDown.Show(Int32 x, Int32 y)
   at System.Windows.Forms.ContextMenuStrip.ShowInTaskbar(Int32 x, Int32 y)
   at System.Windows.Forms.NotifyIcon.ShowContextMenu()
   at System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   at System.Windows.Forms.NotifyIcon.NotifyIconNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   
   
![image](https://user-images.githubusercontent.com/41529240/111140757-b5dd7700-8550-11eb-8ab3-c9ce8442d440.png)

**Comment by KAIJutsu** [comment]
Same problem Here !

I made a clean reinstallation with a new default setup & tested every option one by one. 

The cause seems to be : "slow window detection" option for moment but I cannot guarantee it yet because i need more testing time. 
The trigger of this problem is when the window is reduced in the window taskbar notification. 
When you want to open it again, here the app is freezing.

If there is more ppl with this problem. Post it here pls.

**Comment by Codingale** [comment]
Same issue here, using Slow Window Detection; the other method uses a lot of CPU idle when it's not time sensitive operation I think so I figured I'd do that but nope, just cases it to hang if I re-launch the game.
